"""empty message

Revision ID: 3a993c94cfe9
Revises: f1339464ffea
Create Date: 2025-05-17 12:46:27.989172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a993c94cfe9'
down_revision: Union[str, None] = 'f1339464ffea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_call_admin_team', 'calls', ['admin_id', 'team_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_call_admin_team', 'calls', type_='unique')
    # ### end Alembic commands ###
