"""empty message

Revision ID: a2156a9d55bd
Revises: 
Create Date: 2025-05-16 01:29:53.076338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2156a9d55bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('team_feedback', sa.Integer(), nullable=True),
    sa.Column('admin_feedback', sa.String(), nullable=False, server_default=""),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('img',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('role_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('persons', sa.String(), nullable=True),
    sa.Column('in_progress', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('img')
    op.drop_table('calls')
    # ### end Alembic commands ###
